[package]
name = "my_bevy_game"
version = "0.1.0"
authors = ["Timothée Le Berre <timothee.leberre@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html 

[dependencies]
bevy = { version="0.4", features = ["dynamic"]}
bevy_tilemap = {git = "https://github.com/ryanleecode/bevy_tilemap", branch = "bevy_nightly"}
bevy_dylib = "0.4"
crossbeam-channel = "0.4"
seahash = "=4.0.1"
noise = "=0.6.0"
serde = "1.*"
ron = "0.6.2"