[package]
name = "my_bevy_game"
version = "0.1.0"
authors = ["Timothée Le Berre <timothee.leberre@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { git="https://github.com/bevyengine/bevy"}
seahash = "=4.0.1"
fuss = "=0.2.2"
rand = "=0.7.3"
serde = "1.*"
bevy_tiled = {git = "https://github.com/Imakoala/bevy_tiled"}
tiled_builder = {git = "https://github.com/Imakoala/tiled_builder"}
